# Generated by Django 5.1.2 on 2024-11-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_is_staff_customuser_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(default=1234567890, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
