# Generated by Django 5.1.2 on 2024-11-14 14:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_post_trendingpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingpost',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='TrendingPosts/'),
        ),
    ]
