# Generated by Django 5.1.2 on 2024-10-23 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_stock_product_quantity_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
